/* Generated By:JavaCC: Do not edit this line. GrammerConstants.java */
package simple_language;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Digit = 5;
  /** RegularExpression Id. */
  int Sign = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<Digit>",
    "<Sign>",
    "\":=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"==\"",
    "\"!\"",
    "\"^\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"skip\"",
    "\"ff\"",
    "\"tt\"",
    "<token of kind 22>",
    "<token of kind 23>",
  };

}
